name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GHCR (GitHub Registry)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        # تبدیل نام ریپازیتوری به حروف کوچک (داکر به حروف بزرگ حساس است)
        IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        
        docker build . --file Dockerfile -t $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest

    - name: Trigger Coolify Deploy Webhook
      run: |
        curl -X GET "${{ secrets.COOLIFY_WEBHOOK_URL }}"
